Traceback (most recent call last):
  File "/home/user/mod5/task4/redirect.py", line 41, in <module>
    raise Exception('Hello stderr.txt')
Exception: Hello stderr.txt
